name: weather_scrape

on:
  schedule:
    - cron: '*/5 * * * *'  # Menjadwalkan untuk menjalankan setiap jam
  workflow_dispatch:
    
jobs:
  weather-scrape:
    runs-on: macOS-latest
    env:
      ATLAS_URL: ${{ secrets.ATLAS_URL }}
      ATLAS_COLLECTION: ${{ secrets.ATLAS_COLLECTION }}
      ATLAS_DB: ${{ secrets.ATLAS_DB }}
    steps:
    - name: Start time
      run: echo "$(date) ** $(TZ=Asia/Jakarta date)"
    - uses: actions/checkout@v3
    - uses: r-lib/actions/setup-r@v2   
    - name: Scrape Data Weather
      run: Rscript weather_scrape.R
